# Generated by Django 4.0.2 on 2022-02-16 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='patient',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Residence'),
        ),
        migrations.AddField(
            model_name='patient',
            name='stature',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Stature'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Weight'),
        ),
    ]
